name: 1. Dispatch Discussion Comment Task

on:
  discussion_comment:
    types: [created]

permissions:
  issues: write  # 写入任务队列 Issue
  actions: write # 触发另一个 workflow

jobs:
  dispatch-task:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Add task to central queue
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: 93
          body: |
            TASK::${{ github.event.discussion.number }}::${{ github.event.comment.id }}

      - name: 2. Trigger the processor workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: 2. Process Discussion Task
          token: ${{ secrets.GITHUB_TOKEN }}
          inputs: '{ "discussion_number": "${{ github.event.discussion.number }}" }'
