name: 2. Process Discussion Task

on:
  workflow_dispatch:
    inputs:
      discussion_number:
        description: 'The discussion number to process tasks for'
        required: true
        type: string

# ✨ 魔法在这里！并发组是基于传入的 discussion_number 动态创建的 ✨
concurrency:
  group: process-discussion-${{ github.event.inputs.discussion_number }}
  cancel-in-progress: false

permissions:
  issues: write      # 读写队列 Issue
  discussions: write # 你的实际任务可能需要操作 discussion

jobs:
  process-task:
    runs-on: ubuntu-latest
    steps:
      - name: Process a single task for the discussion
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run: node process.js
